<?php
/**
  ************************************************************************
  WFPHP订单系统版权归WENFEI所有，凡是破解此系统者都会死全家，非常灵验。
  ************************************************************************
  版权声明：凡是破解此系统者、盗卖此系统者在三日内必出车祸死于非命，五日内
  其父母必得绝症不治身亡，七日内老婆儿女将意外身亡，总之全家都不得好死。
  ************************************************************************
  WFPHP订单系统官方网站：http://www.wforder.com/   （盗版盗卖者死全家）
  WFPHP订单系统官方店铺：http://889889.taobao.com/ （破解系统者死全家）
  ************************************************************************
  版权声明：修改删除此注释者不出三日必然意外身亡，非常灵验，不信就试试。
  ************************************************************************
  郑重警告：凡是破解此系统者出门就被车撞死，盗卖此系统者三日内必死全家。
  ************************************************************************ 
 */
session_start();$sid=session_id();error_reporting(0);date_default_timezone_set('PRC');ini_set('default_charset','utf-8');define('WFHOME',preg_replace("/[\/\\\\]{1,}/",'/',dirname(__FILE__)));define('WFORDER',dirname(WFHOME));define('WFDATA',WFORDER.'/wfdata');define('WFPUBLIC',WFORDER.'/wfpublic');require WFDATA.'/wfpublic.php';require WFDATA.'/wfconfig.php';require WFPUBLIC.'/WFzhead.php';require WFPUBLIC.'/WFdblink.php';require WFPUBLIC.'/WFprotemp.php';require WFPUBLIC.'/WFsms.php';require WFPUBLIC.'/WForder.php';$WForder=new WForder();$res=$WForder->wfpostdb();if($res){if($WForder->wfpayment=='alipay'||$WForder->wfpayment=='weixin'||$WForder->wfpayment=='ebank'){$WForder->wfcallback(0,0,$WForder->wfpayurl);foreach($_SESSION as $key=>$val){if($key!='wfuser'&&$key!='wfpassword'&&$key!='subtime'&&$key!='wfddsource'&&$key!='WFLLURL'&&$key!='WFDDURL'){unset($_SESSION[$key]);}}}else{if($WForder->wftempinfo[18]==2){$wfpostokmsg=preg_replace("/\{(.*?)\}/",'".$WForder->$1."',$WForder->wftempinfo[20]);eval("\$wfpostokmsg=\"$wfpostokmsg\";");$WForder->wfcallback($wfpostokmsg,1,0);}else{$wfpostokurl=$WForder->wftempinfo[19]?$WForder->wftempinfo[19]:'../../wfhome/wfsuccess.php?sid='.$sid;$WForder->wfcallback(0,0,$wfpostokurl);}if($wfsms['codon']){$WFsms=new WFsms();$WForder->wfproduct=is_array($_POST['wfproduct'])?implode('/',$_POST['wfproduct']):$_POST['wfproduct'];$wfsmsuserstr=preg_replace("/\{(.*?)\}/",'".$WForder->$1."',$wfsms['coduser']);$wfsmsadminstr=preg_replace("/\{(.*?)\}/",'".$WForder->$1."',$wfsms['codadmin']);eval("\$wfsmsuser=\"$wfsmsuserstr\";");eval("\$wfsmsadmin=\"$wfsmsadminstr\";");$WFsms->wfsendsms($WForder->wfmob,$wfsms['codobj']['u'],$wfsms['codobj']['a'],$wfsmsuser,$wfsmsadmin);}}}else{$WForder->wfalert($WForder->wflang['dataexception'],0,0,0,0);}$dataopt=array('订单号'=>$WForder->wfddno,'下单时间'=>$WForder->wfbuydate,'订购产品'=>$WForder->wfproduct,'产品尺码'=>$WForder->wfprosize,'产品颜色'=>$WForder->wfprocolour,'赠送产品'=>$WForder->wfgiftname,'赠送产品尺码'=>$WForder->wfgiftsize,'赠送产品颜色'=>$WForder->wfgiftcolour,'数量/价格'=>$WForder->wfnums.' / '.$WForder->wfprice,'姓名'=>$WForder->wfname,'性别'=>$WForder->wfsex,'年龄'=>$WForder->wfage,'身高'=>$WForder->wfheight,'体重'=>$WForder->wfweight,'身份证号'=>$WForder->wfidcard,'手机号'=>$WForder->wfmob,'电话号码'=>$WForder->wftel,'详细地址'=>$WForder->wfaddress,'邮编'=>$WForder->wfpost,'QQ号'=>$WForder->wfqq,'微信号'=>$WForder->wfweixin,'邮箱'=>$WForder->wfemail,'邀请码'=>$WForder->wfinvcode,'日期'=>$WForder->wfdatetime,'日期范围'=>$WForder->wfdaterange,'付款方式'=>$WForder->wfpayment,'留言'=>$WForder->wfguest,'广告渠道'=>$WForder->wfddsource,'订单来路'=>$WForder->WFLLURL,'下单页面'=>$WForder->WFDDURL,'搜索关键词'=>$WForder->wfkeyword,'IP地址'=>$WForder->wfipadd);if($wfmail['sendon']){include WFPUBLIC.'/WFmail.php';$WFmail=new WFmail($wfmail);$mailbody='<div style="padding:30px;border:2px solid #FFD699;background:#FFFFF2;">';foreach($dataopt as $key=>$val){if(!empty($val)){$mailbody.='【'.$key.'】'.$val.'<br>';}}$mailbody.='</div>';$WFmail->sendmail($mailbody);}?>