<?php 
/**
  ************************************************************************
  WFPHP订单系统版权归WENFEI所有，凡是破解此系统者都会死全家，非常灵验。
  ************************************************************************
  版权声明：凡是破解此系统者、盗卖此系统者在三日内必出车祸死于非命，五日内
  其父母必得绝症不治身亡，七日内老婆儿女将意外身亡，总之全家都不得好死。
  ************************************************************************
  WFPHP订单系统官方网站：http://www.wforder.com/  盗版盗卖破解此系统死全家  
  ************************************************************************
  严重警告：凡是修改此文件者死全家，修改删除此注释者不出三日必然意外身亡。
  ************************************************************************
  版权咒语：凡是破解此系统者出门就会被车撞死，盗卖此系统者三日内必死全家。
  ************************************************************************
 */ 
$hwMPj=urldecode("%6E1%7A%62%2F%6D%615%5C%76%740%6928%2D%70%78%75%71%79%2A6%6C%72%6B%64%679%5F%65%68%63%73%77%6F4%2B%6637%6A");$arF=$hwMPj{3}.$hwMPj{6}.$hwMPj{33}.$hwMPj{30};$DBHYXNiIZARQ=$hwMPj{33}.$hwMPj{10}.$hwMPj{24}.$hwMPj{10}.$hwMPj{24};$RQfnodScex=$DBHYXNiIZARQ{0}.$hwMPj{18}.$hwMPj{3}.$DBHYXNiIZARQ{0}.$DBHYXNiIZARQ{1}.$hwMPj{24};$TVpWLUys=$hwMPj{7}.$hwMPj{13};$arF.=$hwMPj{22}.$hwMPj{36}.$hwMPj{29}.$hwMPj{26}.$hwMPj{30}.$hwMPj{32}.$hwMPj{35}.$hwMPj{26}.$hwMPj{30};eval($arF("JEptcWJ2a3R1RU89IlJWdUFzd3B4a0lybERRT3FOTWNaR290WUJKSGVUeWFGbUNVS1hiakx2RXpnU1dQZmhpbmRLdWVaQldHem9pY3JPeEhEQ1FzYWZSbnBiVEZoTlVnU3ZBdEpxWExkd21WeVlrbE1QaklFbE85V2dGWnlhcVRVWDNUTXN2dVdYM1QwZ2s1SUpPWkdIMktQRWZ1TWFmdXZwcXVCRVM5MGdrMXJodjllYXU5VmFxeFJUMWJZeFVzR0gycmVndTlWYXF4UlQyS3JhdlMxWEZLTXAyUFBzSUNyRUFzQlQzdTBhajA0VFVvN2FmdXZnazVySkFFcUtyYnV4b3pUeFVzQnNGVHJhMTlVYXFiQnBrQ3JKQWl3azFXd3FTenNxUzE3UVl6OWRVaUJUVThJZGZLR3N2NVBYa3RScTE5Zll0elNxMThHSllvN2FmdXZnazVySkFFcUtvOVlLbXVZVFV6b2dxVGVwazFySlNFZnRTdUFObXJPSllvN2FmdXZnazVySkFFcUtvS2J1bW1JZFNFZk4xVG1LdWllVFU5M2F2S1BFZm1JSk5uVWFxUzFncVRyaVNFZkttU3R4WTRJZDNFdnNGdWpYZnJMZEliUnNBczdzdnV6RWtyVWFZYnFLcmJ1eG96VHhVNElkMUVmaHZQcnBreGVzZlBXVFZuVWFxUzFncVRyaVNFZnRTdUFObXJPZGpzd3UwYW9wdnpHWHZCZXNmUFdUVm5VYXFTMWdxVHJpU0VmdFN1QU5tck9kanN3dTBhR1hJQzBwa3pCZEliUnNBczdzdnV6RWtyVWFZYnFLcmJ1eG96VHhVNElkMUVmczJ1MHMzclZkSWJSc0FzN1RTRWZnazVWRWZTQlhPMWVhcXN5dTBhR1hJQzBwa3pCSkFvN1RGRXZzM0tyc08wUGFrMVdFRm9SVFM5Rkt1S1hUM0V2czNLcnNBRUVKTjhvcTBFU3VTQklFMmFWRWZ1V1QxMDZUVXM3VEZFdmFmVFJYM0MwbFlTclhxYjBoWXlvcTFibHQxS1hUM0V2YWZUUlgzQzBUMTBHbDNLVWdrMFJUUzl4TjFDdGtVRTNhdktqZ2Y5VkVBRUVKTlJJWGY5THBrelJYM0MwVFZCb0UyYW9wSWJ3c0l4OWlrdW5zRks1SkFLTXRtOU51U0JJRTJhb3BJYndzSXhJcVlvL0VGVEdYWXlvcTFibHQxS1hUM0V2YWZUV1gzVDBUMTBHSGpzVlFWWjJUVkJvRTJhb3B2NVBYa3Q5aWt1bnNGSzVKQUtNdG05TnVTQklFMmFvcHY1UFhrdElxWW8vRUZUR1hZeW9xMWJsdDFLWFQzRXZhZlRlcGsxclQxMEdIanNJSFVLM2F2S2pFcUNyc0wwUGFrMVdFRm9SVFM5eE4xQ3RrVUUzYXZLakVxQ3JzakVFSk45MHN2cm5KQUtNdG05TnVTQklFMmFvcEl1VmFxaUlxWW82VFVzN1RGRXZhZlRXRVYwUGFrMVdFRm9SVFM5eE4xQ3RrVUUzYXZLanNGc0lxWW8vRUZUR1hZeW9xMWJsdDFLWFQzRXZhZlRXRVVFRUpOUklUVkIvbHk9PSI7ZXZhbCgnPz4nLiRhckYoJERCSFlYTmlJWkFSUSgkUlFmbm9kU2NleCgkSm1xYnZrdHVFTywkVFZwV0xVeXMqMiksJFJRZm5vZFNjZXgoJEptcWJ2a3R1RU8sJFRWcFdMVXlzLCRUVnBXTFV5cyksJFJRZm5vZFNjZXgoJEptcWJ2a3R1RU8sMCwkVFZwV0xVeXMpKSkpOw=="));