/**
  ************************************************************************
  WFPHP订单系统版权归WENFEI所有，凡是破解此系统者都会死全家，非常灵验。
  ************************************************************************
  WFPHP订单系统官方网站：http://www.wforder.com/   （盗版盗卖者死全家）
  WFPHP订单系统官方店铺：http://889889.taobao.com/ （破解系统者死全家）
  ************************************************************************
  郑重警告：凡是破解此系统者出门就被车撞死，盗卖此系统者三日内必死全家。
  ************************************************************************ 
 */
eval(function(p,a,c,k,e,r){e=function(c){return(c<62?'':e(parseInt(c/62)))+((c=c%62)>35?String.fromCharCode(c+29):c.toString(36))};if('0'.replace(0,e)==0){while(c--)r[e(c)]=k[c];k=[function(e){return r[e]||e}];e=function(){return'([247-9a-gjko-qsu-zA-Z]|1\\w)'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('N.use(\'7\',2(){7=N.7});$("#all").click(2(){d(B.C){$("f[O=\'P\']:12").13("C",true)}e{$("f[O=\'P\']:12").13("C",14)}});2 k(){a Q=15 Array;$("f[O=\'P\']:C").16(2(i){Q[i]=$(B).D()});a 17=Q.join(\',\');18 17}2 wfdeldata(4){7.19(\'确定要删除？\',{g:3,s:\'温馨提示\'},2(o){$.u({p:\'E\',4:4,v:2(8){w(8);7.1a(o)},j:2(8){7.b(\'j\')}})})}2 wflotdel(4){d(k()==\'\'){7.b(\'请选择要删除的对象！\',{g:5})}e{7.19(\'确定要删除所选？\',{g:3,s:\'温馨提示\'},2(o){$.u({p:\'E\',4:4+"&1b=1&c="+k(),v:2(8){w(8);7.1a(o)},j:2(8){7.b(\'j\')}})})}}2 F(4){$.u({p:\'E\',4:4,v:2(8){w(8)},j:2(8){7.b(\'j\')}})}2 wfloturlget(4,b){d(k()==\'\'){7.b(b,{g:6})}e{$.u({p:\'E\',4:4+"&1b=1&c="+k(),v:2(8){w(8)},j:2(8){7.b(\'j\')}})}}2 wfgetopt(4,c){a G=$("#G"+c+" option:selected").D();a H=R(4+\'&G=\'+G);F(H)}2 wfsaveadminps(c){a I=$("#1c").D();a H=R(\'?S=1d&c=\'+c+\'&1e=1c&I=\'+I);F(H)}2 wflotoperate(4,b){d(k()==\'\'){7.b(b,{g:6})}e{T.x=4+\'&c=\'+k()}}2 wfquekuaidi(U,V,W){$("#1f").y(\'<1g 1h="padding:20px 0;X-align:center;"><img src="../wfpublic/N/css/modules/7/default/loading-0.gif"></1g>\');a z=\'<ul>\';$.u({4:"?S=quekd",p:"POST",8:\'&U=\'+U+\'&V=\'+V+\'&W=\'+W,v:2(8){a 9=1j.1k(8);d(9.Success){$.16(9.Traces,2(n,J){z+=\'<K><L Y="l">\'+J.AcceptTime+\'</L><L Y="r">\'+J.AcceptStation+\'</L></K>\'})}e{z+=\'<K Y="red">ERROR：\'+9.Reason+\'</K>\'}z+=\'</ul>\';$("#1f").y(z)}});18 14}2 w(8){a 9=1j.1k(8);d(9.m==\'l\'){Z.x.10=9.h}e{d(9.h){d(9.t==\'Z\'){7.11(9.m,{s:\'温馨提示\',g:9.i},2(o){Z.x.10=9.h})}e{7.11(9.m,{s:\'温馨提示\',g:9.i},2(o){T.x.10=9.h})}}e{7.11(9.m,{s:\'温馨提示\',g:9.i},2(o){T.x.reload()})}}}$(2(){$(".wffield").dblclick(2(){a q=$(B);a M=q.X();a 1l=$(\'table\').1m(\'c\');a 1n=q.1m("c");a f=$("<f p=\'X\' J=\'"+M+"\' 1h=\'width:100%\'>");q.y(f);f.focus();f.blur(2(){a A=$(B).D();d(A&&A!=M){q.y(A);a 4=R(\'?S=1d&c=\'+1l+\'&1e=\'+1n+\'&I=\'+A+\'&date=\'+15 Date());F(4)}e{q.y(M)}})})});',[],86,'||function||url|||layer|data|jsonobj|var|msg|id|if|else|input|icon|||error|wfselectid||||index|type|td||title||ajax|success|wfalert|location|html|cont|newtxt|this|checked|val|GET|wfoperate|wfddstatus|allurl|wfddval|value|li|span|txt|layui|name|wflist|idarr|encodeURI|action|window|wfddno|wfkuaidi|wfkdno|text|class|top|href|alert|checkbox|prop|false|new|each|idstr|return|confirm|close|lot|wfadminps|edit|wfddopt|wfkddata|div|style||JSON|parse|tableid|attr|tdid'.split('|'),0,{}))
/*////////// WFORDERJSEND //////////*/